{% set version = "1.4.7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-guilds
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/GUILDS_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/GUILDS/GUILDS_{{ version }}.tar.gz
  sha256: b9de0a28dd92fdf237df7e94bd9249aecee4c900191f695d6a1136f7b1848f58

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-nloptr                     # [build_platform != target_platform]
    - r-pracma                     # [build_platform != target_platform]
    - r-rcpp >=0.11.0              # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-nloptr
    - r-pracma
    - r-rcpp >=0.11.0
  run:
    - r-base
    - r-nloptr
    - r-pracma
    - r-rcpp >=0.11.0

test:
  commands:
    - $R -e "library('GUILDS')"           # [not win]
    - "\"%R%\" -e \"library('GUILDS')\""  # [win]

about:
  home: https://github.com/thijsjanzen/GUILDS
  license: GPL-2.0-only
  summary: A collection of sampling formulas for the unified neutral model of biogeography and biodiversity. Alongside the sampling formulas, it includes methods to perform maximum likelihood optimization of the sampling formulas, methods to generate data given the neutral model, and methods to estimate the expected species
    abundance distribution. Sampling formulas included in the GUILDS package are the Etienne Sampling Formula (Etienne 2005), the guild sampling formula, where guilds are assumed to differ in dispersal ability (Janzen et al. 2015), and  the guilds sampling formula conditioned on guild size (Janzen et al. 2015).
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - jenzopr
